# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           newbie
Version:        1.0.8
Release:        %autorelease
Summary:        Natural language shell interpreter and text processor

SourceLicense:  MIT
License:        MIT AND MPL-2.0 AND Unicode-3.0

URL:            https://github.com/markallenbattey/Newbie
Source:         https://github.com/markallenbattey/Newbie/archive/%{version}/Newbie-%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
Newbie is a natural language shell interpreter that eliminates traditional
shell complexity through universal ampersand prefixes (&command syntax) and
delimiter-free parsing. Designed for text processing tasks without requiring
knowledge of regex, sed, or grep. Features streaming file processing,
transparent compression support, and an interactive help system.}

%description %{_description}

%prep
%autosetup -n Newbie-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
install -Dpm 644 newbie.1 %{buildroot}%{_mandir}/man1/newbie.1

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.txt
%{_bindir}/newbie
%{_mandir}/man1/newbie.1*

%changelog
%autochangelog
